dist: trusty
language: java
install: true

services:
- docker

sudo: required

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TODO_VERSION=0.0.1

addons:
  chrome: stable

before_install:
- bash .travis.prepare.sh

script:
- bash .travis.build.sh
- bash .travis.deploy.sh

after_script:
- bash .travis.cleanup.sh