version: '3.7'

services:
  static:
    image: veronezi/todo-static:${STATIC_VERSION:-latest}

  auth:
    image: veronezi/auth-jwt:${AUTH_VERSION:-latest}
    ports:
      - "${AUTH_PORT:-3001}:3000"

  ui:
    image: veronezi/todo-facade:${UI_VERSION:-latest}
    ports:
    - "${UI_PORT:-80}:80"
    environment:
    - API_DNS=${API_DNS:-api}
    - STATIC_DNS=${API_DNS:-static}

  api:
    image: veronezi/todo-api:${API_VERSION:-latest}
    ports:
    - "${API_PORT:-8080}:8080"
    environment:
    - WAIT_FOR=db:5432,auth:3000

  db:
    image: veronezi/sample-postgres:${POSTGRES_VERSION:-latest}
    ports:
    - "${DB_PORT:-5432}:5432"
    environment:
    - DEBUG=false
    - POSTGRES_DB=todo
    - POSTGRES_USER=todo_user
    - POSTGRES_PASSWORD=todo_pass

  ft:
    image: veronezi/todo-ft
    environment:
    - WAIT_FOR=api:8080,ui:80,auth:3000
