version: '3.7'

services:
  static:
    image: veronezi/todo-static:${STATIC_VERSION:-latest}

  auth:
    image: veronezi/auth-jwt:${AUTH_VERSION:-latest}

  ui:
    image: veronezi/todo-facade:${UI_VERSION:-latest}
    ports:
    - "${UI_PORT:-80}:80"
    environment:
    - API_DNS=${API_DNS:-api}
    - STATIC_DNS=${API_DNS:-static}

  api:
    image: veronezi/todo-api:${API_VERSION:-latest}
    environment:
    - WAIT_FOR=db:5432,auth:3000

  minio:
    image: veronezi/sample-minio:${MINIO_VERSION:-latest}

  db:
    image: veronezi/sample-postgres:${POSTGRES_VERSION:-latest}
    environment:
      - WAIT_FOR=minio:9000
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=TESTINGACCESS123
      - MINIO_SECRET_KEY=tesTingPass123
      - RESTORE_BASE_BACKUP=${RESTORE_BASE_BACKUP:-}
      - DEBUG=false
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass

  ft:
    image: veronezi/todo-ft
    environment:
    - WAIT_FOR=api:8080,ui:80,auth:3000
