version: '3.1'

services:
  static:
    image: veronezi/todo-static:0.0.1-b68

  auth:
    image: veronezi/todo-auth:0.0.1-b68

  ui:
    image: veronezi/todo-facade:0.0.1-b68
    ports:
      - "80:80"

  api:
    image: veronezi/todo-api:0.0.1-b68
    environment:
      - WAIT_FOR=db:5432,auth:3000

  db:
    image: postgres:10.4
    environment:
      - DEBUG=false
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
