version: '3.1'

services:
  static:
    image: veronezi/todo-static:0.0.1-b57

  auth:
    image: veronezi/todo-auth:0.0.1-b57

  ui:
    image: veronezi/todo-facade:0.0.1-b57
    ports:
      - "80:80"

  api:
    image: veronezi/todo-api:0.0.1-b57
    environment:
      - WAIT_FOR=db:5432,auth:3000
      - CATALINA_OPTS=-Xms128m -Xmx512m
      - DB_URL=db:5432
      - DB_USR=todo_user
      - DB_PWD=todo_pass
      - DB_NAME=todo
      - JWT_AUTH_URI=http://auth:3000/auth

  db:
    image: postgres:10.4
    environment:
      - DEBUG=false
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
